name: rick_and_morty
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter

   # Infrastructure
  flutter_bloc: ^8.1.6
  freezed: ^2.5.7
  built_value: ^8.9.2
  chopper: ^8.0.1+1
  permission_handler: ^11.3.1
  built_collection: ^5.1.1
  freezed_annotation: ^2.4.4
  mask_text_input_formatter: ^2.9.0
  dio: ^5.7.0
  pretty_chopper_logger: ^1.0.9
  web_socket_channel: any
  share_plus: ^10.1.4
  html: ^0.15.5
  connectivity_plus: ^6.1.1
  app_links: ^6.3.2
  upgrader: ^11.2.0
  top_snackbar_flutter: ^3.1.0
  sentry_flutter: ^8.9.0
  device_info_plus: ^11.1.0
  progress_indicators: ^1.0.0
  flutter_svg: ^2.0.11
  flutter_screenutil: ^5.9.3
  bloc: ^8.1.4
  logger: ^2.4.0
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_native_splash: ^2.4.3

  cloud_firestore: ^5.6.9
  flutter_udid: ^3.0.0
  google_api_availability: ^5.0.1
  cached_video_player_plus: ^3.0.1
  flutter_local_notifications: any
  flutter_smart_dialog: ^4.9.8+3
  dots_indicator: ^3.0.0
  dartz: ^0.10.1
  intl: ^0.19.0
  sms_autofill: ^2.4.0
  pin_input_text_field: ^4.5.2
  animated_toggle_switch: ^0.8.3
  geolocator: ^13.0.2
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  build: ^2.4.1
  build_runner: ^2.4.13
  built_value_generator: ^8.9.2
  chopper_generator: ^8.0.3
  google_maps_flutter: ^2.10.0
  sensors_plus: ^6.1.0
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0
  formz: ^0.8.0
  lottie: ^3.3.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.0
  animations: ^2.0.11
  flutter_inappwebview: ^6.1.5

  #image
  image: ^4.0.17
  cached_network_image: ^3.2.3
  path: ^1.9.1
  image_cropper: ^8.0.2
  mime: ^1.0.5
  photo_view: ^0.15.0
  image_picker: ^1.1.2
  easy_localization: ^3.0.7
  camera: ^0.11.0+2
  webview_flutter: ^4.10.0
  #  html_unescape: ^2.0.0
  # photo_manager_image_provider: ^2.2.0
  # extended_image: ^9.0.9
  #  time_slot: ^1.0.0
  #  flutter_rating_bar: ^4.0.1
  #  toggle_switch: ^2.3.0
  #  flutter_widget_from_html: ^0.15.1
  # uuid: ^4.0.0

  package_info_plus: ^8.1.2
  flutter_multi_formatter: ^2.13.0
  carousel_slider: ^5.0.0
  file_utils: ^1.0.1
  open_file: ^3.5.10
  file_picker: ^10.1.2
  simple_gesture_detector: ^0.2.1
  extended_image: ^10.0.1
  flutter_html: ^3.0.0
  http: ^1.4.0
  fluttertoast: ^8.2.12
  flutter_pdfview: ^1.4.1+1
  syncfusion_flutter_pdfviewer: ^30.1.38
  video_player: ^2.10.0
  chewie: ^1.12.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translation/
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#FFFFFF"
  image: assets/images/splash_screen.png
  android_gravity: fill
  ios_content_mode: scaleAspectFill

  android_12:
    image: assets/images/splash_screen.png
    icon_background_color: "#FFFFFF"
    image_dark: assets/images/splash_screen.png
    icon_background_color_dark: "#FFFFFF"
    android_gravity: fill
  android: true
  ios: true  
 


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
